# Generated by Django 3.0.2 on 2020-06-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('TO', 'To SMA'), ('FR', 'From SMA')], max_length=2)),
                ('place_address', models.CharField(max_length=255)),
                ('sma_address', models.CharField(max_length=255)),
                ('fare_type', models.CharField(choices=[('OW', 'One way'), ('RT', 'Rount trip')], max_length=2)),
                ('luggage', models.IntegerField(default=0)),
                ('pickup_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Extra information about your trip', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shuttle.Client')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='shuttle.Place')),
            ],
        ),
    ]
