# Generated by Django 3.0.2 on 2020-06-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0003_auto_20200612_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='place_address',
            new_name='place_details',
        ),
    ]
