# Generated by Django 3.0.2 on 2020-06-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0005_auto_20200613_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateTimeField(blank=True, help_text='Required if fare type is round trip', null=True),
        ),
    ]
