# Generated by Django 3.0.2 on 2020-06-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0006_auto_20200613_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fare_type',
            field=models.CharField(choices=[('OW', 'One way'), ('RT', 'Round trip')], max_length=2),
        ),
    ]
