# Generated by Django 3.0.2 on 2020-06-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0008_reservation_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CA', 'Cash'), ('PP', 'PayPal')], default='CA', max_length=2),
            preserve_default=False,
        ),
    ]
