# Generated by Django 3.0.2 on 2020-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0009_auto_20200620_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
