# Generated by Django 3.0.2 on 2020-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle', '0013_reservation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
